topic: "Should we adopt universal basic income?"
rounds: 5
target_duration_minutes: 13
words_per_turn: 180
speaking_rate_wpm: 155
model: "gpt-4o-mini"
judge_model: "gpt-4o-mini"
tts_model: "tts-1"
voices:
  debater_a: "alloy"
  debater_b: "verse"
  moderator: "sage"
names:
  debater_a: "Aylin"
  debater_b: "Bora"
  moderator: "Moderatör"
judges:
  count: 9
  seed_variation: true
